// Podaci o kursevima
export const allCourses = [
  {
    id: 1,
    title: "Web Programiranje",
    instructor: "Prof. Marko Marković",
    rating: 4.8,
    reviews: 156,
    price: 60,
    image: "/placeholder.svg?height=160&width=300",
    category: "Web Razvoj",
    level: "Početni",
    duration: "12 sedmica",
    date: "2023-05-01",
  },
  {
    id: 2,
    title: "Osnove JavaScript-a",
    instructor: "Dr. Ana Anić",
    rating: 4.5,
    reviews: 120,
    price: 45,
    image: "/placeholder.svg?height=160&width=300",
    category: "Web Razvoj",
    level: "Početni",
    duration: "8 sedmica",
    date: "2023-04-15",
  },
  {
    id: 3,
    title: "React za početnike",
    instructor: "Emir Emirović",
    rating: 4.9,
    reviews: 210,
    price: 70,
    image: "/placeholder.svg?height=160&width=300",
    category: "Web Razvoj",
    level: "Srednji",
    duration: "10 sedmica",
    date: "2023-05-10",
  },
  {
    id: 4,
    title: "Baze podataka",
    instructor: "Prof. Selma Selimović",
    rating: 4.6,
    reviews: 98,
    price: 55,
    image: "/placeholder.svg?height=160&width=300",
    category: "Baze Podataka",
    level: "Početni",
    duration: "8 sedmica",
    date: "2023-03-20",
  },
  {
    id: 5,
    title: "Flutter razvoj aplikacija",
    instructor: "Adnan Adnanović",
    rating: 4.7,
    reviews: 85,
    price: 65,
    image: "/placeholder.svg?height=160&width=300",
    category: "Mobilni Razvoj",
    level: "Srednji",
    duration: "12 sedmica",
    date: "2023-04-05",
  },
  {
    id: 6,
    title: "Python za Data Science",
    instructor: "Dr. Haris Hasić",
    rating: 4.8,
    reviews: 128,
    price: 50,
    image: "/placeholder.svg?height=160&width=300",
    category: "Data Science",
    level: "Početni",
    duration: "10 sedmica",
    date: "2023-05-15",
  },
  {
    id: 7,
    title: "UX/UI Dizajn",
    instructor: "Amina Aminović",
    rating: 4.4,
    reviews: 95,
    price: 45,
    image: "/placeholder.svg?height=160&width=300",
    category: "Dizajn",
    level: "Početni",
    duration: "8 sedmica",
    date: "2023-03-10",
  },
  {
    id: 8,
    title: "Digitalni marketing",
    instructor: "Mirza Mirzić",
    rating: 4.5,
    reviews: 110,
    price: 40,
    image: "/placeholder.svg?height=160&width=300",
    category: "Marketing",
    level: "Početni",
    duration: "6 sedmica",
    date: "2023-02-20",
  },
  {
    id: 9,
    title: "Node.js Backend Razvoj",
    instructor: "Haris Hasanović",
    rating: 4.7,
    reviews: 88,
    price: 65,
    image: "/placeholder.svg?height=160&width=300",
    category: "Web Razvoj",
    level: "Napredni",
    duration: "10 sedmica",
    date: "2023-05-05",
  },
  {
    id: 10,
    title: "SQL Napredne Tehnike",
    instructor: "Prof. Selma Selimović",
    rating: 4.6,
    reviews: 75,
    price: 55,
    image: "/placeholder.svg?height=160&width=300",
    category: "Baze Podataka",
    level: "Napredni",
    duration: "8 sedmica",
    date: "2023-04-10",
  },
  {
    id: 11,
    title: "iOS Razvoj sa Swift",
    instructor: "Adnan Adnanović",
    rating: 4.8,
    reviews: 92,
    price: 75,
    image: "/placeholder.svg?height=160&width=300",
    category: "Mobilni Razvoj",
    level: "Srednji",
    duration: "14 sedmica",
    date: "2023-03-15",
  },
  {
    id: 12,
    title: "Machine Learning Osnove",
    instructor: "Dr. Haris Hasić",
    rating: 4.9,
    reviews: 145,
    price: 80,
    image: "/placeholder.svg?height=160&width=300",
    category: "Data Science",
    level: "Srednji",
    duration: "12 sedmica",
    date: "2023-05-20",
  },
  {
    id: 13,
    title: "Adobe Photoshop za Početnike",
    instructor: "Amina Aminović",
    rating: 4.5,
    reviews: 105,
    price: 40,
    image: "/placeholder.svg?height=160&width=300",
    category: "Dizajn",
    level: "Početni",
    duration: "6 sedmica",
    date: "2023-02-15",
  },
  {
    id: 14,
    title: "SEO Optimizacija",
    instructor: "Mirza Mirzić",
    rating: 4.6,
    reviews: 88,
    price: 45,
    image: "/placeholder.svg?height=160&width=300",
    category: "Marketing",
    level: "Srednji",
    duration: "4 sedmice",
    date: "2023-04-25",
  },
  {
    id: 15,
    title: "Poslovno Planiranje",
    instructor: "Jasmina Jasminović",
    rating: 4.7,
    reviews: 65,
    price: 50,
    image: "/placeholder.svg?height=160&width=300",
    category: "Poslovanje",
    level: "Početni",
    duration: "6 sedmica",
    date: "2023-03-05",
  },
  {
    id: 16,
    title: "Finansijski Menadžment",
    instructor: "Jasmina Jasminović",
    rating: 4.8,
    reviews: 72,
    price: 60,
    image: "/placeholder.svg?height=160&width=300",
    category: "Poslovanje",
    level: "Srednji",
    duration: "8 sedmica",
    date: "2023-04-20",
  },
]

// Kategorije kurseva
export const categories = [
  "Svi kursevi",
  "Web Razvoj",
  "Mobilni Razvoj",
  "Baze Podataka",
  "Data Science",
  "Dizajn",
  "Marketing",
  "Poslovanje",
]

// Opcije sortiranja
export const sortOptions = [
  { value: "newest", label: "Najnovije" },
  { value: "oldest", label: "Najstarije" },
  { value: "price-asc", label: "Cijena (rastuće)" },
  { value: "price-desc", label: "Cijena (opadajuće)" },
  { value: "rating-asc", label: "Ocjena (rastuće)" },
  { value: "rating-desc", label: "Ocjena (opadajuće)" },
]
