// Podaci o kursevima korisnika
export const userCourses = [
  {
    id: 1,
    title: "Web Programiranje",
    instructor: "Prof. Marko Marković",
    progress: 75,
    image: "/placeholder.svg?height=160&width=300",
    lastAccessed: "2023-05-12",
    lastAccessedFormatted: "12.05.2023.",
    status: "U toku",
    category: "Web Razvoj",
  },
  {
    id: 2,
    title: "Osnove JavaScript-a",
    instructor: "Dr. Ana Anić",
    progress: 45,
    image: "/placeholder.svg?height=160&width=300",
    lastAccessed: "2023-05-10",
    lastAccessedFormatted: "10.05.2023.",
    status: "U toku",
    category: "Web Razvoj",
  },
  {
    id: 3,
    title: "React za početnike",
    instructor: "Emir Emirović",
    progress: 90,
    image: "/placeholder.svg?height=160&width=300",
    lastAccessed: "2023-05-15",
    lastAccessedFormatted: "15.05.2023.",
    status: "U toku",
    category: "Web Razvoj",
  },
  {
    id: 4,
    title: "Baze podataka",
    instructor: "Prof. Selma Selimović",
    progress: 30,
    image: "/placeholder.svg?height=160&width=300",
    lastAccessed: "2023-05-08",
    lastAccessedFormatted: "08.05.2023.",
    status: "U toku",
    category: "Baze Podataka",
  },
  {
    id: 5,
    title: "Mobilni razvoj sa Flutter",
    instructor: "Adnan Adnanović",
    progress: 60,
    image: "/placeholder.svg?height=160&width=300",
    lastAccessed: "2023-05-14",
    lastAccessedFormatted: "14.05.2023.",
    status: "U toku",
    category: "Mobilni Razvoj",
  },
  {
    id: 6,
    title: "Python za Data Science",
    instructor: "Dr. Haris Hasić",
    progress: 15,
    image: "/placeholder.svg?height=160&width=300",
    lastAccessed: "2023-05-05",
    lastAccessedFormatted: "05.05.2023.",
    status: "U toku",
    category: "Data Science",
  },
  {
    id: 7,
    title: "UX/UI Dizajn",
    instructor: "Amina Aminović",
    progress: 5,
    image: "/placeholder.svg?height=160&width=300",
    lastAccessed: "2023-05-03",
    lastAccessedFormatted: "03.05.2023.",
    status: "Nije započeto",
    category: "Dizajn",
  },
  {
    id: 8,
    title: "HTML i CSS Osnove",
    instructor: "Prof. Marko Marković",
    progress: 100,
    image: "/placeholder.svg?height=160&width=300",
    lastAccessed: "2023-04-20",
    lastAccessedFormatted: "20.04.2023.",
    status: "Završeni",
    category: "Web Razvoj",
  },
  {
    id: 9,
    title: "Digitalni marketing",
    instructor: "Mirza Mirzić",
    progress: 100,
    image: "/placeholder.svg?height=160&width=300",
    lastAccessed: "2023-03-15",
    lastAccessedFormatted: "15.03.2023.",
    status: "Završeni",
    category: "Marketing",
  },
  {
    id: 10,
    title: "Poslovno Planiranje",
    instructor: "Jasmina Jasminović",
    progress: 0,
    image: "/placeholder.svg?height=160&width=300",
    lastAccessed: "2023-05-01",
    lastAccessedFormatted: "01.05.2023.",
    status: "Nije započeto",
    category: "Poslovanje",
  },
]

// Statusi kurseva
export const statuses = ["Svi", "U toku", "Završeni", "Nije započeto"]

// Opcije sortiranja
export const sortOptions = [
  { value: "last-accessed", label: "Zadnje pristupljeno" },
  { value: "progress-asc", label: "Napredak (rastuće)" },
  { value: "progress-desc", label: "Napredak (opadajuće)" },
  { value: "title-asc", label: "Naziv (A-Z)" },
  { value: "title-desc", label: "Naziv (Z-A)" },
]
